name: Feature request
description: Propón una mejora o nueva funcionalidad
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: "Motivación"
      placeholder: "¿Por qué debería añadirse esta mejora?"
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "Propuesta"
      placeholder: "Describe la funcionalidad que te gustaría añadir."
    validations:
      required: true
